# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_plswork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Card')),
                ('numberInDeck', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=50, verbose_name='Suit')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Card Value')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Suit')),
            ],
        ),
    ]
